Add ical Link
DU4L/CTFNote pull request #31
Opened 2022-02-07 18:21 UTC by frereit

Sorry about the huge commit :/

* Adds a /calendar.ics?key=[....] endpoint where all CTFs are available in iCal Format
* The frontend calendar now shows a link to the iCal
* The key used for the calendar can be changed in the Admin Dashboard
Above changes by @B-i-t-K

To make this work, I had to do some minor fixes and make /calendar.ics available through the nginx proxy in front (and quasar config for development).

I also removed graphql files from eslint because we dropped the graphql eslint plugin.

This will close #30 and #9

2022-02-07 21:51 UTC, JM-Lemmi commented
Build of api fails because of missing `ical-generator` plugin

```
Step 9/27 : RUN yarn run build
 ---> Running in 05b874d9d7b6
yarn run v1.22.15
$ tsc
src/routes/ical.ts(1,30): error TS2307: Cannot find module 'ical-generator' or its corresponding type declarations.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'api' failed to build : The command '/bin/sh -c yarn run build' returned a non-zero code: 2
``

2022-02-07 22:04 UTC, frereit commented
Good catch, I still had it installed from previous tests.

2022-02-07 22:16 UTC, JM-Lemmi requested changes
Database errors on fresh start:

```
db_1        | 2022-02-07 22:06:00.818 UTC [81] ERROR:  permission denied for table settings
db_1        | 2022-02-07 22:06:00.818 UTC [81] STATEMENT:  with __local_0__ as (select to_json((json_build_object('__identifiers'::text, json_build_array(__local_1__."unique_id"), 'registrationAllowed'::text, (__local_1__."registration_allowed"), 'registrationPasswordAllowed'::text, (__local_1__."registration_password_allowed"), 'style'::text, (__local_1__."style")))) as "@nodes" from (select __local_1__.*
db_1        |   from "ctfnote"."settings" as __local_1__
db_1        | 
db_1        |   where (TRUE) and (TRUE)
db_1        |   order by __local_1__."unique_id" ASC
db_1        | 
db_1        |   ) __local_1__), __local_2__ as (select json_agg(to_json(__local_0__)) as data from __local_0__) select coalesce((select __local_2__.data from __local_2__), '[]'::json) as "data"
```

2022-02-08 16:28 UTC, frereit commented
Okay, I have reproduced the issue and am working on it.

Interestingly enough, it doesn't happen on [https://github.com/DU4L/CTFNote/tree/upstream-ical-link], the branch that's compatible with the upstream dev branch.

2022-02-08 21:10 UTC, JM-Lemmi approved these changes

2022-02-09 16:18 UTC, merged